name: Run Tests

on:
  push:
    branches:
      - feature/dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Check Test Results
        run: |
          # Verifique se os testes falharam
          if [[ "$?" -ne 0 ]]; then
            echo "Testes falharam. Pipeline quebrada."
            exit 1
          fi
